FROM debian

ADD debian.list /etc/apt/sources.list.d/


RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p krapiva.com/img && \
    chmod -R 754 /var/www/krapiva.com/ && \
    useradd Kate  && groupadd Krapivina && usermod -a -G Krapivina Kate  && \
    chown -R Kate :Krapivina /var/www/krapiva.com && \
    sed -i 's$/var/www/html$/var/www/krapiva.com$g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Kate /g' /etc/nginx/nginx.conf
	
ADD index.html /var/www/krapiva.com/
ADD img.jpg /var/www/krapiva.com/img/
CMD ["nginx", "-g", "daemon off;"]